apiVersion: v1
kind: Pod
metadata:
  name: log-generator-pod
  labels:
    app: log-generator
spec:
  containers:
  - name: log-generator-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "APP_ERROR: Failed to connect to database on port 5432" >&2;
          echo "APP_WARNING: Cache refresh timed out after 30s";
          echo "INFO: Application running normally";
          sleep 5;
        done
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "20Mi"
        cpu: "20m"
